### ISSUE TITLE
Any chance to adjust the Air Quality Sensor?

### ISSUE THREAD

**Issue by Krocko** [joe-ng/homebridge-dyson-link#7]
I have a Netatmo weather station in the same room. The Air Quality Sensor from the Dyson shows the Air quality one step better as the Netatmo Modul. Is it possible to adjust this value?

**Comment by joe-ng** [comment]
The way that Dyson air quality sensor works was that it offered two air quality value, dust and voc level, and we just do an average of two numbers to get set the air quality. (the higher the worst of air quality)
While I am not sure how your Netatmo device showed air quality, one thing I can do is to make the "sensitivity" adjustable so that we may multiply the dust/voc average to lower the overall quality.
Would that work for you?

**Comment by Krocko** [comment]
Yes of course, we can try it.

**Comment by joe-ng** [comment]
I have added that to the latest version and you may configure the sensitivity from the config file. Default is 1 and you may change that to 1.5, 2.0 etc for that -

        {
          "ip": "ip of your second device",
          "displayName": "Name to be shown on Home App",
          "serialNumber": "DYSON-XXX-XX-XXXXXXXX-XXX",
          "password": "password of your second device",
          "sensitivity": 1 // the higher, the worse air quality level
        }

**Comment by Krocko** [comment]
Thank you very much @joe-ng.
Works like a charm.
